// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pitstop.LuggageManagment.DataAccess;

namespace Pitstop.LuggageManagment.Migrations
{
    [DbContext(typeof(LuggageManagmentDBContext))]
    partial class LuggageManagmentDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Pitstop.LuggageManagment.Model.Luggage", b =>
                {
                    b.Property<string>("LuggageId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PassengerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Weight")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LuggageId");

                    b.HasIndex("PassengerId");

                    b.ToTable("Luggage");
                });

            modelBuilder.Entity("Pitstop.LuggageManagment.Model.Passenger", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Passenger");
                });

            modelBuilder.Entity("Pitstop.LuggageManagment.Model.Luggage", b =>
                {
                    b.HasOne("Pitstop.LuggageManagment.Model.Passenger", null)
                        .WithMany("Luggage")
                        .HasForeignKey("PassengerId");
                });

            modelBuilder.Entity("Pitstop.LuggageManagment.Model.Passenger", b =>
                {
                    b.Navigation("Luggage");
                });
#pragma warning restore 612, 618
        }
    }
}
